export const countryPhoneCodes = [
  { country: "India", code: "+91", flag: "https://flagcdn.com/in.svg" },
  { country: "United States", code: "+1", flag: "https://flagcdn.com/us.svg" },
  { country: "Canada", code: "+1", flag: "https://flagcdn.com/ca.svg" },
  { country: "Mexico", code: "+52", flag: "https://flagcdn.com/mx.svg" },
  { country: "Brazil", code: "+55", flag: "https://flagcdn.com/br.svg" },
  { country: "United Kingdom", code: "+44", flag: "https://flagcdn.com/gb.svg" },
  { country: "Germany", code: "+49", flag: "https://flagcdn.com/de.svg" },
  { country: "France", code: "+33", flag: "https://flagcdn.com/fr.svg" },
  { country: "Italy", code: "+39", flag: "https://flagcdn.com/it.svg" },
  { country: "Spain", code: "+34", flag: "https://flagcdn.com/es.svg" },
  { country: "Russia", code: "+7", flag: "https://flagcdn.com/ru.svg" },
  { country: "China", code: "+86", flag: "https://flagcdn.com/cn.svg" },
  { country: "Japan", code: "+81", flag: "https://flagcdn.com/jp.svg" },
  { country: "South Korea", code: "+82", flag: "https://flagcdn.com/kr.svg" },
  { country: "Australia", code: "+61", flag: "https://flagcdn.com/au.svg" },
  { country: "New Zealand", code: "+64", flag: "https://flagcdn.com/nz.svg" },
  { country: "South Africa", code: "+27", flag: "https://flagcdn.com/za.svg" },
  { country: "Nigeria", code: "+234", flag: "https://flagcdn.com/ng.svg" },
  { country: "Egypt", code: "+20", flag: "https://flagcdn.com/eg.svg" },
  { country: "Saudi Arabia", code: "+966", flag: "https://flagcdn.com/sa.svg" },
  { country: "United Arab Emirates", code: "+971", flag: "https://flagcdn.com/ae.svg" },
  { country: "Turkey", code: "+90", flag: "https://flagcdn.com/tr.svg" },
  { country: "Argentina", code: "+54", flag: "https://flagcdn.com/ar.svg" },
  { country: "Chile", code: "+56", flag: "https://flagcdn.com/cl.svg" },
  { country: "Colombia", code: "+57", flag: "https://flagcdn.com/co.svg" },
  { country: "Venezuela", code: "+58", flag: "https://flagcdn.com/ve.svg" },
  { country: "Thailand", code: "+66", flag: "https://flagcdn.com/th.svg" },
  { country: "Vietnam", code: "+84", flag: "https://flagcdn.com/vn.svg" },
  { country: "Philippines", code: "+63", flag: "https://flagcdn.com/ph.svg" },
  { country: "Indonesia", code: "+62", flag: "https://flagcdn.com/id.svg" },
  { country: "Malaysia", code: "+60", flag: "https://flagcdn.com/my.svg" },
  { country: "Singapore", code: "+65", flag: "https://flagcdn.com/sg.svg" },
  { country: "Pakistan", code: "+92", flag: "https://flagcdn.com/pk.svg" },
  { country: "Bangladesh", code: "+880", flag: "https://flagcdn.com/bd.svg" },
  { country: "Sri Lanka", code: "+94", flag: "https://flagcdn.com/lk.svg" },
  { country: "Nepal", code: "+977", flag: "https://flagcdn.com/np.svg" },
  { country: "Greece", code: "+30", flag: "https://flagcdn.com/gr.svg" },
  { country: "Netherlands", code: "+31", flag: "https://flagcdn.com/nl.svg" },
  { country: "Belgium", code: "+32", flag: "https://flagcdn.com/be.svg" },
  { country: "Austria", code: "+43", flag: "https://flagcdn.com/at.svg" },
  { country: "Switzerland", code: "+41", flag: "https://flagcdn.com/ch.svg" },
  { country: "Sweden", code: "+46", flag: "https://flagcdn.com/se.svg" },
  { country: "Norway", code: "+47", flag: "https://flagcdn.com/no.svg" },
  { country: "Denmark", code: "+45", flag: "https://flagcdn.com/dk.svg" },
  { country: "Finland", code: "+358", flag: "https://flagcdn.com/fi.svg" },
  { country: "Portugal", code: "+351", flag: "https://flagcdn.com/pt.svg" },
  { country: "Poland", code: "+48", flag: "https://flagcdn.com/pl.svg" },
  { country: "Czech Republic", code: "+420", flag: "https://flagcdn.com/cz.svg" },
  { country: "Hungary", code: "+36", flag: "https://flagcdn.com/hu.svg" },
  { country: "Israel", code: "+972", flag: "https://flagcdn.com/il.svg" },
  { country: "Ireland", code: "+353", flag: "https://flagcdn.com/ie.svg" }
];
